### ISSUE TITLE
Missing datasets

### ISSUE THREAD

**Issue by alamin25264alamin25264** [RubenVG02/AntibioticsDiscovery#7]
I'm trying to run your code and using this code for a computational biology research. Would you please provide me the datasets so i can run the code and try to solve my problem as well.

**Comment by RubenVG02** [comment]
Hi! In order to use the pre-trained models, you can use the BindingDB inhibition database (https://www.bindingdb.org/bind/downloads/BindingDB_BindingDB_Inhibition_202304.tsv.zip), and you can correct your data for the CNN using the "fix_data_models.py" script, and for the RNN you can use the "smiles_22.txt" file in the txt_files, although I personally recommend you to train your models yourself, depending on your objectives. There are also some text files in order to do so. 
If you need help with something else, just let me know.

**Comment by alamin25264alamin25264** [comment]
Hello Ruben,
Thank you very much for your quick response. I'm glad you have shown me a
way to start the run. Still, I would request you to please provide me the
text files; I will use them if necessary. I would like to reach out to you
further if any help is needed regarding the current issue.

Kind regards,
Alamin
ᐧ

**Comment by RubenVG02** [comment]
Hi Alamin,
Hope you are doing great. As I previously said, you can find the files for the RNN model (the one to generate molecules) inside the txt_files folder. The one I used for my model was "smiles_22.txt", although I recommend you train your own model with other data (which can be found inside this folder more_training_files_rnn folder. On the other hand, you can download the data I used for the CNN model here (https://mega.nz/file/JbMmgbqK#REY5afsZTc3A0l21zZKHU48GhQGEwThVyq5pRnrmTzU), which have been obtained from BindingDB.
If you need something else, let me know.

**Comment by alamin25264alamin25264** [comment]
Hello Ruben,
Thank you again for the response and help. I will go on with the analysis,
and if any help is needed, I will reach out to you.
Kind regards,
Alamin
ᐧ
